---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true

- name: Install Vim
  apt:
    pkg: vim
    state: present
    update_cache: true
  become: yes
